server:
  port: 8080
spring:
  profiles:
    active: dev
  datasource:
    admin:
      jdbc-url: jdbc:mysql://localhost:3306/from_zero_admin
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
    content:
      jdbc-url: jdbc:mysql://localhost:3306/from_zero_content
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
